### ISSUE TITLE
urldecode the returned value?

### ISSUE THREAD

**Issue by mtalvenheimo** [electrickite/paramStash#2]
Hi,

Is it possible to urldecode the returned value?

**Comment by electrickite** [comment]
You can use any MODX output filter with the snippet, so you could do something like this:

```
[[!paramStash:urldecode? &params=`foo` &valueOnly=`1`]]
```

See the MODX docs for more information: https://rtfm.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/input-and-output-filters-(output-modifiers)

**Comment by mtalvenheimo** [comment]
Ok. That worked. thank you.
